language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
    - riak
    - mongodb
    - memcached
    - redis-server

before_install:
    - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then pecl install riak-beta; fi"
    - sh -c "if [[ $TRAVIS_PHP_VERSION != 'hhvm' && `php-config --vernum` -ge 50500 ]] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ; else echo 'extension="apc.so"' >> ./tests/travis/php.ini ;fi"
    - composer self-update
    - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/travis/php.ini; fi"

install:
    - composer --prefer-source --dev install

script:
    - ./vendor/bin/phpunit -c ./tests/travis/phpunit.travis.xml -v

after_script:
    - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
